# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.provider.date:
        class: AppBundle\Provider\DateProvider

    app.service.date:
        class: AppBundle\Service\DateService
        calls:
            - [setDateProvider, ['@app.provider.date']]
